# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  deploy-to-coopernetes:
    docker:
      - image: colabcoop/coopernetes-deploy:0.3.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: |
        cd .deploy
        helmfile --log-level debug apply

workflows:
   deploy:
     jobs:
       - deploy-to-coopernetes:
           context: coopernetes-staging
           #           filters:
           #             branches:
           #               only: develop
