apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.image.port }}
        {{- with .Values.image.env}}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.name }}-image-pull-secret
