apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}

spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.name }}-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name }}
          servicePort: 80
