releases:
  - name: hello-voter
    namespace: hello-voter
    chart: ./chart
    values:
      - name: hello-voter
        issuer: "letsencrypt-prod"
        host: hello-voter.coopernetes.colab.coop
        image:
          tag: {{ requiredEnv "DOCKER_TAG" }}
          port: 80
        imageCredentials:
          registry: https://index.docker.io/v1/
          username: { requiredEnv "DOCKER_USER" }
          password: { requiredEnv "DOCKER_PASSWORD" }
          email: devops+dockerhub@colab.coop
